PREFIX res:  <http://dbpedia.org/resource/>
PREFIX dbp:  <http://dbpedia.org/property/>
PREFIX dbo:  <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?o
where {
    res:Salt_Lake_City dbo:timeZone ?uri .
    ?uri rdfs:label ?

    filter (lang(?o) = 'en')
}

===

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?uri
WHERE {
    ?cave rdf:type dbo:Cave ; dbo:location ?uri .
    ?uri rdf:type dbo:Country
}
GROUP BY ?uri
HAVING ( COUNT(?cave) > 2 )

===

select distinct ?s
where {
  ?s a <http://schema.org/Restaurant>
}

===

prefix dbr:  <http://dbpedia.org/resource/>
prefix dbo:  <http://dbpedia.org/ontology/>
prefix foaf: <http://xmlns.com/foaf/0.1/>

select distinct ?o
where {
  ?s a <http://schema.org/Restaurant> .
  dbr:Locanda_Locatelli dbo:address ?o
  # name
}
