version: '3.5'
services:
  quira-brainz-virtuoso:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../datasets/quira-brainz:/usr/share/proj/quira
    ports:
      - 1111:1111
      - 8890:8890
